[build]
  base = "frontend"
  publish = "build"
  functions = "./functions"
  command = "npm install && npm run build"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"

