[build]
  base = "frontend"
  publish = "build"
  command = "npm install && npm run build"

[functions]
  directory = "../functions"  

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
