[build]
  base = "/"
  publish = "frontend/build"
  command = "npm install && npm run build"

[functions]
  directory = "functions"  

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"